Tensor 생성하기 (P19)

In [ ]:
import torch                                                        # PyTorch 라이브러리를 추가

print(torch.cuda.is_available())                                    # cuda를 활용한 gpu 연산이 가능한지 확인
print(torch.tensor([1,2,3,4,5,6]))                                  # 1차원 벡터 형태의 Tensor 생성
print(torch.tensor([[1,2,3],[4,5,6]], device="cuda:0"))             # 2차원 형태의 Tensor를 GPU에 생성
print(torch.tensor([[[1,2],[3,4],[5,6]]], dtype=torch.float64))     # 3차원 형태의 Tensor를 float64의 형식으로 생성

: 

생성한 Tensor의 타입 확인하기 (P20)

In [19]:
print("type of [1,2,3,4,5,6]\t\t : ", torch.tensor([1,2,3,4,5,6]).type())
print("type of [1.2,2,3,4,5,6]\t\t : ", torch.tensor([1.2,2,3,4,5,6]).type())
print("type of [[[1,2],[3,4],[5,6]]]\t : ", torch.tensor([[[1,2],[3,4],[5,6]]], dtype=torch.float64).type())


type of [1,2,3,4,5,6]		 :  torch.LongTensor
type of [1.2,2,3,4,5,6]		 :  torch.FloatTensor
type of [[[1,2],[3,4],[5,6]]]	 :  torch.DoubleTensor


Tensor의 numpy() method를 통한 ndarray 변환(P 21)

In [25]:
tmp_tensor = torch.tensor([[1,2],[3,4]])

print("matrix tensor\t\t : ",tmp_tensor)
arr = tmp_tensor.numpy()

print("ndarray translation\t : ", arr)

matrix tensor		 :  tensor([[1, 2],
        [3, 4]])
ndarray translation	 :  [[1 2]
 [3 4]]


In [26]:
tmp_gpu_tensor = torch.tensor([[1,2],[3,4]], device="cuda:0")

print("matrix tensor\t\t : ",tmp_gpu_tensor)
arr_gpu = tmp_gpu_tensor.numpy()

print("ndarray translation\t : ", arr_gpu)

matrix tensor		 :  tensor([[1, 2],
        [3, 4]], device='cuda:0')


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [27]:
tmp_gpu_tensor = torch.tensor([[1,2],[3,4]], device="cuda:0")

print("matrix tensor\t\t : ",tmp_gpu_tensor)
arr_gpu_1 = tmp_gpu_tensor.cpu().numpy()
arr_gpu_2 = tmp_gpu_tensor.to('cpu').numpy()

print("ndarray translation\t : ", arr_gpu_1)
print("ndarray translation\t : ", arr_gpu_2)

matrix tensor		 :  tensor([[1, 2],
        [3, 4]], device='cuda:0')
ndarray translation	 :  [[1 2]
 [3 4]]
ndarray translation	 :  [[1 2]
 [3 4]]


Tensor의 인덱싱(P 22)

In [30]:
tensor_matrix = torch.tensor([[1,2,3],[4,5,6]])

print("print matrix 1 row, 1 col\t : ",tensor_matrix[1][1], tensor_matrix[-1][1])
print("print matrix 0 row, all col\t : ", tensor_matrix[0,:])
print("print matrix all row, 0 col\t : ", tensor_matrix[:,0])

print matrix 1 row, 1 col	 :  tensor(5) tensor(5)
print matrix 0 row, all col	 :  tensor([1, 2, 3])
print matrix all row, 0 col	 :  tensor([1, 4])


Tensor의 연산(P 23)

In [61]:
tensor1 = torch.FloatTensor([[1,3],[2,4]])
tensor2 = torch.DoubleTensor([[1,3],[2,4]])

print("tensor1 type\t : ", tensor1.type())
print("tensor2 type\t : ", tensor2.type())

sub_tensor = tensor1 - tensor2
add_tensor = tensor1 + tensor2
mul_int_tensor = tensor1 * 2
mul_float_tensor = tensor1 * 2.5
divide_tensor = tensor1 / tensor2
elmentwise_tensor = tensor1 * tensor2

print(sub_tensor)
print(add_tensor)
print(mul_int_tensor)
print(mul_float_tensor)
print(divide_tensor)
print(elmentwise_tensor)



tensor1 type	 :  torch.FloatTensor
tensor2 type	 :  torch.DoubleTensor
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[2., 6.],
        [4., 8.]], dtype=torch.float64)
tensor([[2., 6.],
        [4., 8.]])
tensor([[ 2.5000,  7.5000],
        [ 5.0000, 10.0000]])
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[ 1.,  9.],
        [ 4., 16.]], dtype=torch.float64)


In [69]:
multiply_tensor_1 = tensor1.matmul(tensor2)

print(multiply_tensor_1)

RuntimeError: expected scalar type Float but found Double

In [79]:
multiply_tensor_2 = tensor1.matmul(tensor2.float())
multiply_tensor_3 = tensor1.to(torch.double).matmul(tensor2)

print("float_tensor\t : ", multiply_tensor_2)
print("float_tensor type\t : ", multiply_tensor_2.type())
print("double_tensor\t : ", multiply_tensor_3)
print("double_tensor type\t : ", multiply_tensor_3.type())

float_tensor	 :  tensor([[ 7., 15.],
        [10., 22.]])
float_tensor type	 :  torch.FloatTensor
double_tensor	 :  tensor([[ 7., 15.],
        [10., 22.]], dtype=torch.float64)
double_tensor type	 :  torch.DoubleTensor


Tensor의 차원 조작(P 24)

In [127]:
tensor_matrix_2 = torch.tensor([[1,2,3,4],[5,6,7,8]])

reshape_tensor_1 = tensor_matrix_2.view(-1)
reshape_tensor_2 = tensor_matrix_2.view(2,-1)
reshape_tensor_3 = tensor_matrix_2.view(4,-1)
reshape_tensor_4 = tensor_matrix_2.view(2,2,2)
reshape_tensor_5 = tensor_matrix_2.reshape(8,-1)

print("view(-1) result\t : ", reshape_tensor_1)
print("view(2,-1) result\t : ", reshape_tensor_2)
print("view(4,-1) result\t : ", reshape_tensor_3)
print("view(2,2,2) result\t : ", reshape_tensor_4)
print("reshape(2,2,2) result\t : ", reshape_tensor_5)


view(-1) result	 :  tensor([1, 2, 3, 4, 5, 6, 7, 8])
view(2,-1) result	 :  tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
view(4,-1) result	 :  tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
view(2,2,2) result	 :  tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
reshape(2,2,2) result	 :  tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])


Tensor의 차원 생성 및 제거(P 25)

In [42]:
random_tensor = torch.randn(1,3,1,4)
print("random tensor shape \t\t : ",random_tensor.shape)
squeeze_random1 = random_tensor.squeeze()
squeeze_random2 = random_tensor.squeeze(2)


print("squeeze tensor shape \t\t : ",squeeze_random1.shape)
print("squeeze 2 idx tensor shape \t : ",squeeze_random2.shape)

unsqueeze_random1 = squeeze_random1.unsqueeze(0)
unsqueeze_random2 = squeeze_random1.unsqueeze(1)
unsqueeze_random3 = squeeze_random1.unsqueeze(2)
unsqueeze_random4 = squeeze_random1.unsqueeze(0).unsqueeze(2)


print("unsqueeze 0 idx \t\t : ", unsqueeze_random1.shape)
print("unsqueeze 1 idx \t\t : ", unsqueeze_random2.shape)
print("unsqueeze 2 idx \t\t : ", unsqueeze_random3.shape)
print("unsqueeze 0, 2 idx \t\t : ", unsqueeze_random4.shape)

random tensor shape 		 :  torch.Size([1, 3, 1, 4])
squeeze tensor shape 		 :  torch.Size([3, 4])
squeeze 2 idx tensor shape 	 :  torch.Size([1, 3, 4])
unsqueeze 0 idx 		 :  torch.Size([1, 3, 4])
unsqueeze 1 idx 		 :  torch.Size([3, 1, 4])
unsqueeze 2 idx 		 :  torch.Size([3, 4, 1])
unsqueeze 0, 2 idx 		 :  torch.Size([1, 3, 1, 4])


Tensor의 결합-cat(P 26)

In [56]:
rand_tensor1 = torch.randn(3, 5)
rand_tensor2 = torch.randn(4, 5)
rand_tensor3 = torch.randn(3, 2)
concat_tensor1 = torch.cat([rand_tensor1, rand_tensor2], dim=0)
print("(3,5) + (4, 5) idx 0 \t\t : ",concat_tensor1.shape)
concat_tensor2 = torch.cat([rand_tensor1, rand_tensor3], dim=1)
print("(3,5) + (3, 2) idx 0 \t\t : ",concat_tensor2.shape)

rand_tensor4 = torch.randn(1,1,4)
rand_tensor5 = torch.randn(5,1,4)

concat_tensor4 = torch.cat([rand_tensor4, rand_tensor5], dim=0)
print("(1, 1, 4) + (5, 1, 4) idx 0 \t : ",concat_tensor4.shape)


concat_tensor5 = torch.cat([rand_tensor1, rand_tensor2], dim=1)
print(concat_tensor5.shape)



(3,5) + (4, 5) idx 0 		 :  torch.Size([7, 5])
(3,5) + (3, 2) idx 0 		 :  torch.Size([3, 7])
(1, 1, 4) + (5, 1, 4) idx 0 	 :  torch.Size([6, 1, 4])


RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 4 for tensor number 1 in the list.

Tensor의 결합-stack(P 27)

In [66]:
same_size_tensor1 = torch.randn(3, 5)
same_size_tensor2 = torch.randn(3, 5)


tensor_stack1 = torch.stack([rand_tensor1, rand_tensor2], dim=0)
print("stack (3,5) + (3,5) idx 0 \t : ", tensor_stack1.shape)
tensor_stack2 = torch.stack([rand_tensor1, rand_tensor2], dim=1)
print("stack (3,5) + (3,5) idx 1 \t : ", tensor_stack2.shape)
tensor_stack3 = torch.stack([rand_tensor1, rand_tensor2], dim=2)
print("stack (3,5) + (3,5) idx 2 \t : ", tensor_stack3.shape)

tensor_stack4 = torch.stack([rand_tensor1, rand_tensor2], dim=3)
print("stack (3,5) + (3,5) idx 2 \t : ", tensor_stack4.shape)



stack (3,5) + (3,5) idx 0 	 :  torch.Size([2, 3, 5])
stack (3,5) + (3,5) idx 1 	 :  torch.Size([3, 2, 5])
stack (3,5) + (3,5) idx 2 	 :  torch.Size([3, 5, 2])


IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)